gocam_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

pombase/urls.py
from django.contrib import admin
from django.urls import include, path

import os

urlpatterns = [
    path('gocam_viz/', include('gocam_viz.urls')),
    path('gocam_view/', include('gocam_view.urls')),
    path('gocam_connections/', include('gocam_connections.urls')),
    path('gocam_app/', include('gocam_app.urls')),
]

if len(os.environ["WEBSITE_CONFIG_JSON_PATH"]) > 0:
    urlpatterns.append(path('motifsearch/', include('motifsearch.urls')))
    urlpatterns.append(path('gene_ex/', include('gene_ex.urls')))
    urlpatterns.append(path('structure_view/', include('structure_view.urls')))
    urlpatterns.append(path('rna_2d_structure/', include('rna_2d_structure.urls')))
    urlpatterns.append(path('protein_feature_view/', include('protein_feature_view.urls')))
    urlpatterns.append(path('rhea_widget/', include('rhea_widget.urls')))
    urlpatterns.append(path('stats/', include('stats.urls')))
    urlpatterns.append(path('admin/', admin.site.urls))

stats/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('cumulative_curated_by_year/',
         views.cumulative_curated_by_year,
         name='cumulative_curated_by_year'),
    path('curated_by_year/',
         views.curated_by_year,
         name='curated_by_year'),
    path('curatable_by_year/',
         views.curatable_by_year,
         name='curatable_by_year'),
    path('ltp_genes_per_pub_per_year_range',
         views.ltp_genes_per_pub_per_year_range,
         name='ltp_genes_per_pub_per_year_range'),
    path('ltp_annotations_per_pub_per_year_range',
         views.ltp_annotations_per_pub_per_year_range,
         name='ltp_annotations_per_pub_per_year_range'),
    path('htp_annotations_per_pub_per_year_range',
         views.htp_annotations_per_pub_per_year_range,
         name='htp_annotations_per_pub_per_year_range'),
    path('community_response_rates',
         views.community_response_rates,
         name='community_response_rates'),
    path('cumulative_annotation_type_counts_by_year',
         views.cumulative_annotation_type_counts_by_year,
         name='cumulative_annotation_type_counts_by_year'),
    path('cumulative_micropublications_by_year',
         views.cumulative_micropublications_by_year,
         name='cumulative_micropublications_by_year')
]

gocam_app/forms.py
from django import forms

class IdForm(forms.Form):
    ids = forms.CharField(label=False, widget=forms.Textarea(attrs={'class': 'ids-field'}))
    dag = forms.BooleanField(label="Use top-down layout", required=False)

gocam_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

import urllib.parse
import re

from .forms import IdForm

def index(request):
    app_path = request.GET.get('app_path', '').strip()
    api_path = request.GET.get('api_path', '').strip()

    context = {
        'app_path': app_path,
        'api_path': api_path,
    }

    if request.method == "POST":
        form = IdForm(request.POST)
        if form.is_valid():
            ids = form.cleaned_data["ids"].replace("\n", " ")
            ids = ids.replace("gomodel:", "");

            ids = re.sub(r'(?:\s|[,;])+', '+', ids)
            if not form.cleaned_data["dag"]:
                ids = 'B+' + ids
            ids = urllib.parse.quote_plus(ids)

            url = f"{app_path}/view/{ids}:show_models"

            return HttpResponseRedirect(url)

    else:
        form = IdForm()

    context["form"] = form

    return render(request, "gocam_app/index.html", context)

gocam_app/templates/gocam_app/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GO-CAMs</title>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">

    <style>
      body {
        margin-left: 1em;
        font-size: 140%;
      }
      #id_ids {
        width: 40em;
        height: 20em;
      }
      #ids-submit {
        margin-top: 1em;
        font-size: 110%;
      }
      #missing-activities table {
        border-collapse: collapse;
        width: 95%;
      }
      #missing-activities thead {
        border-bottom: 3px solid #ccc;
      }
      #missing-activities {
        font-size: 90%;
      }
      #missing-activities td, #missing-activities th {
        vertical-align: top;
        padding: 0.4em;
      }
      #missing-activities tr:nth-child(2n+1) {
        background-color: #f3f3fa;
      }
      .ids-field {
        display: block;
      }
   </style>
  </head>
  <body>
    <h4>Links:</h4>

    <ul>
      <li>
        <a href="{{app_path}}/view/ALL_CONNECTED:show_models">All connected models</a>
      </li>
      <li>
        <a href="{{app_path}}/view/ALL_MERGED:show_models">All models</a>
      </li>
      <li>
        <a href="{{app_path}}/summary/connected_only">Summary map of connected models</a>
      </li>
      <li>
        <a href="{{app_path}}/summary/all_models">Summary map of all models</a>
      </li>
    </ul>
    
    <h4>Create a diagram from IDs:</h4>

    <form id="id-lookup" action="" method="post">
      {% csrf_token %}
      <div>
        {{ form }}
      </div>
      <input id="ids-submit" type="submit" value="View GO-CAM(s)">
    </form>

    <h4>Missing activities</h4>
    <div id="missing-activities">
  <table>
    <thead>
      <tr>
        <th>
          Pathway
        </th>
        <th>
          Missing activity
        </th>
        <th>
          Process
        </th>
        <th>
          Input/output
        </th>
        <th>
          Occurs in
        </th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
    </div>

    <script type="module">
const makeLink = (id, label, title) => {
  const bits = id.split(":");
  if (bits.length == 2) {
    if (bits[0] == 'PomBase') {
      return `<a target="_blank" href="/gene/${bits[1]}">${label}</a>`;
    }
    if (bits[0] == 'FB') {
      return `<a target="_blank" href="https://www.flybase.org/reports/${bits[1]}">${label}</a>`;
    }
    if (bits[0] == 'CHEBI') {
      return `<a target="_blank" href="https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=${id}">${label} (${id})</a>`;
    }
    if (bits[0] == 'GO') {
      return `<a target="_blank" href="https://amigo.geneontology.org/amigo/term/${id}">${label} (${id})</a>`;
    }
    if (bits[0].startsWith('gomodel')) {
      const modelId = bits[1];
      let href = `${appPath}/view/${modelId}`;
      return `<a target="_blank" href="${href}">${label}</a>`;
    }
  }

  return label;
};

const appPath = '{{app_path}}';
const apiPath = '{{api_path}}';
const holesUrl = `${apiPath}/missing_activities`;
const response = await fetch(holesUrl);
const holes = await response.json();
const holesDiv = document.querySelector('#missing-activities');
const tbody = holesDiv.querySelector('tbody');

for (const hole of holes) {
  const rowEl = document.createElement("tr");
  tbody.appendChild(rowEl);
  let [longModelId, modelTitle] = hole.models[0];
  const modelId = longModelId.replace('gomodel:', '');

  const modelEl = document.createElement("td");
  rowEl.appendChild(modelEl);
  const modelHtml = makeLink(longModelId, modelTitle);
  modelEl.insertAdjacentHTML('afterbegin', modelHtml);

  const missingActivityEl = document.createElement("td");
  rowEl.appendChild(missingActivityEl);
  const missingActivityHtml = makeLink(hole.node_id, hole.label);
  missingActivityEl.insertAdjacentHTML('afterbegin', missingActivityHtml);

  const processEl = document.createElement("td");
  rowEl.appendChild(processEl);
  const processHtml = makeLink(hole.part_of_process.id, hole.part_of_process.label);
  processEl.insertAdjacentHTML('afterbegin', processHtml);

  let inputs = hole.has_input.map(input => makeLink(input.id, input.label)).join(',');
  if (inputs.length == 0) {
    inputs = '?';
  }
  let outputs = hole.has_output.map(output => makeLink(output.id, output.label)).join(',');
  if (outputs.length == 0) {
    outputs = '?';
  }
  const inputOutputEl = document.createElement("td");
  rowEl.appendChild(inputOutputEl);
  inputOutputEl.insertAdjacentHTML('afterbegin', inputs + ' / ' + outputs);

  const occursInEl = document.createElement("td");
  rowEl.appendChild(occursInEl);
  const occursInHtml = hole.occurs_in.map(occurs_in => {
    const component = occurs_in.complex_component || occurs_in.other_component;
    return makeLink(component.id, component.label);
  }).join(',');
  occursInEl.insertAdjacentHTML('afterbegin', occursInHtml);
}
    </script>
  </body>
</html>